name: Ganti Tampilan Web Nginx

on:
  workflow_dispatch:

jobs:
  update-web:
    runs-on: self-hosted
    steps:
      - name: Eksekusi Ganti Tulisan
        run: |
          sudo kubectl exec deployment/web-belajar -- sh -c "echo '<h1>Woy Bree! Web ini berubah otomatis dari GitHub loh!</h1><p>Gokil, lo sekarang udah jadi Master CI/CD.</p>' > /usr/share/nginx/html/index.html"
