name: Ganti Tampilan Web Nginx - Versi Galak

on:
  workflow_dispatch:

jobs:
  update-web:
    runs-on: self-hosted
    steps:
      - name: Cari Tau Lokasi File
        run: |
          # Kita cek dulu Nginx lo nyimpen filenya di mana
          sudo kubectl exec deployment/web-belajar -- ls /usr/share/nginx/html/
          
      - name: Paksa Ganti File Index
        run: |
          # Kita pake perintah 'tee' biar lebih mantap tembusnya
          sudo kubectl exec deployment/web-belajar -- sh -c "echo '<h1>Woy Bree! Ini update ke-2. Kalo ini muncul, berarti kita sukses!</h1>' | tee /usr/share/nginx/html/index.html"
          
      - name: Restart Nginx di dalem Pod
        run: |
          # Kadang Nginx butuh disenggol biar baca file baru
          sudo kubectl exec deployment/web-belajar -- nginx -s reload
